//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DHRSoftphone.Plugins.ProcessKiller.BlackWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BlackWS.BlackListSoap")]
    public interface BlackListSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadProcessLog", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void UploadProcessLog(string computername, string fullname, string keywords, string windowsname, string processname, string processpath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/blackList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DHRSoftphone.Plugins.ProcessKiller.BlackWS.ProgramBlackList blackList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBlackList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DHRSoftphone.Plugins.ProcessKiller.BlackWS.ProgramBlackList[] GetBlackList(string fullname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProgramBlackList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long blockApplication_IdField;
        
        private string applicationNameField;
        
        private string windowNameField;
        
        private bool isMustBeSameField;
        
        private string fileNameField;
        
        private bool matchFileNameField;
        
        private bool matchWindowNameField;
        
        private string exceptionUsersField;
        
        private string memoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long BlockApplication_Id {
            get {
                return this.blockApplication_IdField;
            }
            set {
                this.blockApplication_IdField = value;
                this.RaisePropertyChanged("BlockApplication_Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ApplicationName {
            get {
                return this.applicationNameField;
            }
            set {
                this.applicationNameField = value;
                this.RaisePropertyChanged("ApplicationName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string WindowName {
            get {
                return this.windowNameField;
            }
            set {
                this.windowNameField = value;
                this.RaisePropertyChanged("WindowName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool IsMustBeSame {
            get {
                return this.isMustBeSameField;
            }
            set {
                this.isMustBeSameField = value;
                this.RaisePropertyChanged("IsMustBeSame");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("FileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool MatchFileName {
            get {
                return this.matchFileNameField;
            }
            set {
                this.matchFileNameField = value;
                this.RaisePropertyChanged("MatchFileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool MatchWindowName {
            get {
                return this.matchWindowNameField;
            }
            set {
                this.matchWindowNameField = value;
                this.RaisePropertyChanged("MatchWindowName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ExceptionUsers {
            get {
                return this.exceptionUsersField;
            }
            set {
                this.exceptionUsersField = value;
                this.RaisePropertyChanged("ExceptionUsers");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Memo {
            get {
                return this.memoField;
            }
            set {
                this.memoField = value;
                this.RaisePropertyChanged("Memo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BlackListSoapChannel : DHRSoftphone.Plugins.ProcessKiller.BlackWS.BlackListSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BlackListSoapClient : System.ServiceModel.ClientBase<DHRSoftphone.Plugins.ProcessKiller.BlackWS.BlackListSoap>, DHRSoftphone.Plugins.ProcessKiller.BlackWS.BlackListSoap {
        
        public BlackListSoapClient() {
        }
        
        public BlackListSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BlackListSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BlackListSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BlackListSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void UploadProcessLog(string computername, string fullname, string keywords, string windowsname, string processname, string processpath) {
            base.Channel.UploadProcessLog(computername, fullname, keywords, windowsname, processname, processpath);
        }
        
        public DHRSoftphone.Plugins.ProcessKiller.BlackWS.ProgramBlackList blackList() {
            return base.Channel.blackList();
        }
        
        public DHRSoftphone.Plugins.ProcessKiller.BlackWS.ProgramBlackList[] GetBlackList(string fullname) {
            return base.Channel.GetBlackList(fullname);
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
    }
}
